[tool.poetry]
name = "ftp-protocol"
version = "0.1.0"
description = ""
authors = ["Piter N. <gabrielliendo1257@gamil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
