[tool.poetry]
name = "command"
version = "0.1.0"
description = ""
authors = ["Piter N. <gabrielliendo1257>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
